version: "3"

services:
  thoughts_proxy_server:
    image: thoughts_proxy_server
    build: .
    ports:
      - "${UI_PORT}:80"
    networks:
      - thoughts_app
      - nginx_network

networks:
  thoughts_app:
    external: true
  nginx_network:
    external: true
